AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-express-api

  An AWS Lambda project set up with Node.js, TypeScript, Express, and AWS SAM.

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/api.handler
      Events:
        ExpressApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ExpressApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/api.ts

Outputs:
  ExpressApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
